{
  "hash": "edf419062b315885c5eedb2608447168",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Lab 4: Spatial Predictive Analysis\"\nsubtitle: \"Analyzing 311 Violations\"\nauthor: \"Wesley Nay\"\ndate: today\nformat: \n  html:\n    code-fold: show\n    toc: true\n    toc-location: left\n    theme: cosmo\n    embed-resources: true\nexecute:\n  warning: false\n  message: false\n---\n\n# Introduction\n\nIn this analysis, I choose to work with Vacant or Abandoned Buildings Reported as the violation type. Given my interest in housing and economic development as well as having grown up in Chicago, I am curious to see where these reported violations occur and build a model that may be able to predict which areas of the city are likely to have vacant or abandoned buildings.\n\n# Set Up\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Load required packages\nlibrary(tidyverse)      # Data manipulation\nlibrary(sf)             # Spatial operations\nlibrary(here)           # Relative file paths\nlibrary(viridis)        # Color scales\nlibrary(terra)          # Raster operations (replaces 'raster')\nlibrary(spdep)          # Spatial dependence\nlibrary(FNN)            # Fast nearest neighbors\nlibrary(MASS)           # Negative binomial regression\nlibrary(patchwork)      # Plot composition (replaces grid/gridExtra)\nlibrary(knitr)          # Tables\nlibrary(kableExtra)     # Table formatting\nlibrary(classInt)       # Classification intervals\n\n\n# Spatstat for analyzing point patterns - split into sub-packages\nlibrary(spatstat.geom)    # Spatial geometries\nlibrary(spatstat.explore) # Spatial exploration/KDE\n\n# Set options\noptions(scipen = 999)  # No scientific notation\nset.seed(5080)         # Reproducibility, could be any number\n\n# Create consistent theme for visualizations\ntheme_vacant <- function(base_size = 11) {\n  theme_minimal(base_size = base_size) +\n    theme(\n      plot.title = element_text(face = \"bold\", size = base_size + 1),\n      plot.subtitle = element_text(color = \"gray30\", size = base_size - 1),\n      legend.position = \"right\",\n      panel.grid.minor = element_blank(),\n      axis.text = element_blank(),\n      axis.title = element_blank()\n    )\n}\n\n# Set as default\ntheme_set(theme_vacant())\n\ncat(\"✓ All packages loaded successfully!\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n✓ All packages loaded successfully!\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"✓ Working directory:\", getwd(), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n✓ Working directory: C:/PPA/GitHub/cpln5920/labs/lab_4 \n```\n\n\n:::\n:::\n\n\n# Part 1: Data Loading and Exploration\n\n## 1.1 Data Loading\n\nHere, I am loading my 311 data and my Chicago spatial boundaries. I am loading in police districts, police beats, the Chicago city boundary, and vacant or abandoned buildings reported from 311 service requests downloaded from OpenData Chicago. I also do some basic data cleaning such as removing rows without coordinates and making the data spatial by transforming it using st_as_sf. I transformed all spatial layers to EPSG:3435 so they shared a common projected coordinate system appropriate for Chicago-area analysis.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Load police districts (used for spatial cross-validation)\npoliceDistricts <- \n  st_read(\"https://data.cityofchicago.org/api/geospatial/24zt-jpfn?method=export&format=GeoJSON\") %>%\n  st_transform(3435) %>%\n  dplyr::select(District = dist_num)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `OGRGeoJSON' from data source \n  `https://data.cityofchicago.org/api/geospatial/24zt-jpfn?method=export&format=GeoJSON' \n  using driver `GeoJSON'\nSimple feature collection with 25 features and 2 fields\nGeometry type: MULTIPOLYGON\nDimension:     XY\nBounding box:  xmin: -87.94011 ymin: 41.64455 xmax: -87.52414 ymax: 42.02303\nGeodetic CRS:  WGS 84\n```\n\n\n:::\n\n```{.r .cell-code}\n# Load police beats (smaller administrative units)\npoliceBeats <- \n  st_read(\"https://data.cityofchicago.org/api/geospatial/n9it-hstw?method=export&format=GeoJSON\") %>%\n  st_transform(3435) %>%\n  dplyr::select(Beat = beat_num)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `OGRGeoJSON' from data source \n  `https://data.cityofchicago.org/api/geospatial/n9it-hstw?method=export&format=GeoJSON' \n  using driver `GeoJSON'\nSimple feature collection with 277 features and 4 fields\nGeometry type: MULTIPOLYGON\nDimension:     XY\nBounding box:  xmin: -87.94011 ymin: 41.64455 xmax: -87.52414 ymax: 42.02303\nGeodetic CRS:  WGS 84\n```\n\n\n:::\n\n```{.r .cell-code}\n# Load Chicago boundary\nchicagoBoundary <- \n  st_read(\"https://raw.githubusercontent.com/urbanSpatial/Public-Policy-Analytics-Landing/master/DATA/Chapter5/chicagoBoundary.geojson\") %>%\n  st_transform(3435)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `chicagoBoundary' from data source \n  `https://raw.githubusercontent.com/urbanSpatial/Public-Policy-Analytics-Landing/master/DATA/Chapter5/chicagoBoundary.geojson' \n  using driver `GeoJSON'\nSimple feature collection with 1 feature and 1 field\nGeometry type: POLYGON\nDimension:     XY\nBounding box:  xmin: -87.8367 ymin: 41.64454 xmax: -87.52414 ymax: 42.02304\nGeodetic CRS:  WGS 84\n```\n\n\n:::\n\n```{.r .cell-code}\n# Load Vacant and Abandoned Buildings Reported Data from 311 Service Requests (open data)\nvacant_buildings <- read_csv(\"data/311_Service_Requests_-_Vacant_and_Abandoned_Buildings_Reported_-_Historical_20260406.csv\")\n\n# remove rows with no  coordinates\nvacant_buildings <- vacant_buildings %>%\n   drop_na(`X COORDINATE`, `Y COORDINATE`)\n\nvacancies <- st_as_sf(\n  vacant_buildings,\n  coords = c(\"X COORDINATE\", \"Y COORDINATE\"),\n  crs = 3435 #using 3435 because that is the CRS that the vacant buildings dataset is in\n)\n\n# rename columns for easier read and manipulation\nvacancies <- vacancies %>%\n  rename(police_district = 'Police District',\n         community_area = 'Community Area',\n         request_num = 'SERVICE REQUEST NUMBER',\n         date = 'DATE SERVICE REQUEST WAS RECEIVED',\n         vacancy_status = 'IS THE BUILDING CURRENTLY VACANT OR OCCUPIED?')\n\n# Check the data\ncat(\"  - CRS:\", st_crs(vacancies)$input, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  - CRS: EPSG:3435 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"✓ Loaded spatial boundaries\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n✓ Loaded spatial boundaries\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  - Number of vacant or abandoned buildings:\", nrow(vacancies), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  - Number of vacant or abandoned buildings: 65082 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  - Police districts:\", nrow(policeDistricts), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  - Police districts: 25 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  - Police beats:\", nrow(policeBeats), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  - Police beats: 277 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  - Date range:\", format(min(vacancies$date, na.rm = TRUE)), \"to\", \n    format(max(vacancies$date, na.rm = TRUE)), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  - Date range: 01/01/2011 to 12/31/2017 \n```\n\n\n:::\n:::\n\n\n::: callout-note\n### Data Examination\n\nThere are **65,082** vacant or abandoned building service requests in the dataset. The dataset covers the time range from January 1, 2011 through December 31, 2017. I transformed this data into CRS 3435 (Illinois East State Plane) because it is designed specifically for the Chicago region, providing accurate distance and area measurements.\n:::\n\n## 1.2 Spatial Distribution\n\nNext, I am creating visualizations to view the spatial distribution of vacant or abandoned buildings in Chicago. I am creating a simple point map, where each dot represents a vacant or abandoned building, and a density surface map to visualize any hot spots or clustering of these vacant/abandoned buildings.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Simple point map\np1 <- ggplot() + \n  geom_sf(data = chicagoBoundary, fill = \"gray95\", color = \"gray60\") +\n  geom_sf(data = vacancies, color = \"#d62828\", size = 0.1, alpha = 0.4) +\n  labs(\n    title = \"Vacant & Abandoned Buildings\",\n    subtitle = paste0(\"Chicago 2011-2017, n = \", nrow(vacancies))\n  )\n\n# Density surface using modern syntax\np2 <- ggplot() + \n  geom_sf(data = chicagoBoundary, fill = \"gray95\", color = \"gray60\") +\n  geom_density_2d_filled(\n    data = data.frame(st_coordinates(vacancies)),\n    aes(X, Y),\n    alpha = 0.7,\n    bins = 8\n  ) +\n  scale_fill_viridis_d(\n    option = \"plasma\",\n    direction = -1,\n    guide = \"none\"  # Modern ggplot2 syntax (not guide = FALSE)\n  ) +\n  labs(\n    title = \"Density Surface\",\n    subtitle = \"Kernel density estimation\"\n  )\n\n\n# Combine plots using patchwork (modern approach)\np1 + p2 + \n  plot_annotation(\n    title = \"Spatial Distribution of Vacant and Abandoned Buildings in Chicago\",\n    tag_levels = 'A'\n  )\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/visualizations-1.png){width=960}\n:::\n:::\n\n\n::: callout-note\n### Spatial Distribution & Patterns\n\nThe simple point map of vacant and abandoned buildings shows that there are reports of these buildings throughout Chicago. Because there are so many data points, the the kernel density estimation map better visualizes spatial patterns of these reports. In the density surface map, a few hot spots emerge around the city, especially on the south side and slightly less on the west side, while there are no hot spots on the north side or downtown. This indicates a spatial pattern to vacant and abandoned buildings in Chicago. Chicago is a highly segregated city, and the south and west sides are generally home to larger concentrations of Black and Latine communities. The north side of the city has pockets of ethnic enclaves but is generally whiter and wealthier than the south and west sides of the city. This uneven spatial distribution likely reflects broader histories of disinvestment, segregation, and uneven neighborhood conditions across Chicago.\n:::\n\n# Part 2: Fishnet Grid Creation\n\n## 2.1 Creating the Fishnet\n\nNext, I am creating a fishnet grid.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# 500 meters in feet\ncell_size_ft <- 500 * 3.28084\n\nfishnet <- st_make_grid(\n  chicagoBoundary,\n  cellsize = cell_size_ft,\n  square = TRUE\n) %>%\n  st_sf() %>%\n  mutate(uniqueID = row_number())\n\n# Keep only cells that intersect Chicago\nfishnet <- fishnet[chicagoBoundary, ]\n\ncat(\"✓ Created fishnet grid\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n✓ Created fishnet grid\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  - Number of cells:\", nrow(fishnet), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  - Number of cells: 2458 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  - Cell size:\", round(cell_size_ft, 2), \"feet (~500 meters)\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  - Cell size: 1640.42 feet (~500 meters)\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  - Cell area:\", round(as.numeric(st_area(fishnet[1,]))), \"square feet\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  - Cell area: 2690978 square feet\n```\n\n\n:::\n:::\n\n\n## 2.2 Aggregating Vacancy Reports to the Grid\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Spatial join: which cell contains each vacant/abandoned building?\nvacancies_fishnet <- st_join(vacancies, fishnet, join = st_within) %>%\n  st_drop_geometry() %>%\n  group_by(uniqueID) %>%\n  summarize(countVacancies = n(), .groups = \"drop\")\n\nfishnet <- fishnet %>%\n  left_join(vacancies_fishnet, by = \"uniqueID\") %>%\n  mutate(countVacancies = replace_na(countVacancies, 0))\n\ncat(\"\\nVacant or Abandoned Buildings count distribution:\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nVacant or Abandoned Buildings count distribution:\n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(fishnet$countVacancies)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n   0.00    1.00    7.00   26.47   28.00  378.00 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"\\nCells with zero vacant or abandoned buildings:\",\n    sum(fishnet$countVacancies == 0),\n    \"/\", nrow(fishnet),\n    \"(\", round(100 * sum(fishnet$countVacancies == 0) / nrow(fishnet), 1), \"%)\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCells with zero vacant or abandoned buildings: 542 / 2458 ( 22.1 %)\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot() +\n  geom_sf(data = fishnet, aes(fill = countVacancies), color = NA) +\n  geom_sf(data = chicagoBoundary, fill = NA, color = \"white\", linewidth = 1) +\n  scale_fill_viridis_c(\n    name = \"Vacant or Abandoned Buildings\",\n    option = \"plasma\",\n    trans = \"sqrt\",\n    breaks = c(0, 1, 5, 10, 20, 40, 80)\n  ) +\n  labs(\n    title = \"Count of Vacant/Abandoned Buildings by Grid Cell\",\n    subtitle = \"Approximately 500m x 500m cells, Chicago 2011–2017\"\n  ) +\n  theme_vacant()\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-2-1.png){width=672}\n:::\n:::\n\n\n# Part 3: Spatial Features\n\n## 3.1 KDE Baseline\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Convert vacancy points to spatstat point pattern\nvacancy_coords <- st_coordinates(vacancies)\n\nvacancies_ppp <- ppp(\n  x = vacancy_coords[, 1],\n  y = vacancy_coords[, 2],\n  window = as.owin(st_bbox(chicagoBoundary))\n)\n\n# KDE with 1 km bandwidth = 3280.84 feet\nkde_vacancies <- density.ppp(\n  vacancies_ppp,\n  sigma = 3280.84,\n  edge = TRUE\n)\n\n# Convert KDE to terra raster\nkde_raster <- rast(kde_vacancies)\n\n# Extract average KDE value to fishnet cells\nfishnet$kde_value <- terra::extract(\n  kde_raster,\n  vect(fishnet),\n  fun = mean,\n  na.rm = TRUE\n)[, 2]\n\ncat(\"✓ Calculated KDE baseline\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n✓ Calculated KDE baseline\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot() +\n  geom_sf(data = fishnet, aes(fill = kde_value), color = NA) +\n  geom_sf(data = chicagoBoundary, fill = NA, color = \"white\", linewidth = 1) +\n  scale_fill_viridis_c(\n    name = \"KDE Value\",\n    option = \"plasma\"\n  ) +\n  labs(\n    title = \"Kernel Density Estimation Baseline\",\n    subtitle = \"Spatial smoothing of vacant and abandoned building reports\"\n  ) +\n  theme_vacant()\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-4-1.png){width=672}\n:::\n:::\n\n\n## 3.2 k-Nearest Neighbor Features\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Get centroid coordinates for each fishnet cell\nfishnet_centroids <- st_centroid(fishnet)\nfishnet_coords <- st_coordinates(fishnet_centroids)\n\n# Find 5 nearest neighboring cells for each cell\nknn_5 <- get.knn(fishnet_coords, k = 5)\n\n# Calculate mean vacancy count in neighboring cells\nfishnet$vacancies_knn_mean <- purrr::map_dbl(1:nrow(fishnet), function(i) {\n  neighbor_ids <- knn_5$nn.index[i, ]\n  mean(fishnet$countVacancies[neighbor_ids], na.rm = TRUE)\n})\n\nsummary(fishnet$vacancies_knn_mean)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n   0.00    3.80    9.80   26.89   32.35  266.20 \n```\n\n\n:::\n:::\n\n\nThe k-nearest neighbor feature summarizes vacancy counts in nearby grid cells, capturing local spatial context. The distribution shows that while many areas have relatively low neighboring vacancy counts, some cells are surrounded by much higher levels of vacancy, indicating localized clustering. This variable helps the model account for spatial dependence, where vacancy reports in one location are influenced by nearby conditions.\n\n## 3.3 Local Moran's I\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create spatial weights from 5 nearest neighbors\ncoords <- st_coordinates(st_centroid(fishnet))\nneighbors <- knn2nb(knearneigh(coords, k = 5))\nweights <- nb2listw(neighbors, style = \"W\", zero.policy = TRUE)\n\n# Calculate Local Moran's I on vacancy counts\nlocal_moran <- localmoran(fishnet$countVacancies, weights)\n\n# Mean count and spatial lag\nmean_count <- mean(fishnet$countVacancies, na.rm = TRUE)\nlag_count <- lag.listw(weights, fishnet$countVacancies, zero.policy = TRUE)\n\n# Add results and classify clusters\nfishnet <- fishnet %>%\n  mutate(\n    local_i = local_moran[, 1],\n    p_value = local_moran[, 5],\n    is_significant = p_value < 0.05,\n    moran_class = case_when(\n      !is_significant ~ \"Not Significant\",\n      local_i > 0 & countVacancies > mean_count & lag_count > mean_count ~ \"High-High\",\n      local_i > 0 & countVacancies <= mean_count & lag_count <= mean_count ~ \"Low-Low\",\n      local_i < 0 & countVacancies > mean_count & lag_count <= mean_count ~ \"High-Low\",\n      local_i < 0 & countVacancies <= mean_count & lag_count > mean_count ~ \"Low-High\",\n      TRUE ~ \"Not Significant\"\n    )\n  )\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot() +\n  geom_sf(data = fishnet, aes(fill = moran_class), color = NA) +\n  scale_fill_manual(\n    values = c(\n      \"High-High\" = \"#d7191c\",\n      \"High-Low\" = \"#fdae61\",\n      \"Low-High\" = \"#abd9e9\",\n      \"Low-Low\" = \"#2c7bb6\",\n      \"Not Significant\" = \"gray90\"\n    ),\n    name = \"Cluster Type\"\n  ) +\n  labs(\n    title = \"Local Moran's I: Vacancy Report Clusters\",\n    subtitle = \"High-High cells indicate hot spots of vacancy reports\"\n  ) +\n  theme_vacant()\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-7-1.png){width=672}\n:::\n:::\n\n\nThe Local Moran’s I results identify clusters of vacant building reports concentrated primarily on the South and West sides of Chicago. These high-high clusters indicate areas where high vacancy counts are surrounded by similarly high neighboring counts, suggesting strong spatial concentration. This pattern reinforces earlier observations that vacancy reports are not randomly distributed but instead occur in localized hot spots across the city.\n\n## 3.4 Distance to Hot Spots\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhotspots <- fishnet %>%\n  filter(moran_class == \"High-High\") %>%\n  st_centroid()\n\nif (nrow(hotspots) > 0) {\n  fishnet <- fishnet %>%\n    mutate(\n      dist_to_hotspot = as.numeric(\n        st_distance(st_centroid(fishnet), hotspots %>% st_union())\n      )\n    )\n\n  cat(\"✓ Calculated distance to vacancy-report hot spots\\n\")\n  cat(\"  - Number of hot spot cells:\", nrow(hotspots), \"\\n\")\n} else {\n  fishnet <- fishnet %>%\n    mutate(dist_to_hotspot = 0)\n\n  cat(\"⚠ No significant hot spots found\\n\")\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n✓ Calculated distance to vacancy-report hot spots\n  - Number of hot spot cells: 303 \n```\n\n\n:::\n:::\n\n\n# Part 4: Count Regression Models\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Join district information to fishnet\nfishnet <- st_join(\n  fishnet,\n  policeDistricts,\n  join = st_within,\n  left = TRUE\n) %>%\n  filter(!is.na(District))\n\ncat(\"✓ Joined police districts\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n✓ Joined police districts\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  - Districts:\", length(unique(fishnet$District)), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  - Districts: 22 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  - Cells:\", nrow(fishnet), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  - Cells: 1708 \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create clean modeling dataset\nfishnet_model <- fishnet %>%\n  st_drop_geometry() %>%\n  dplyr::select(\n    uniqueID,\n    District,\n    countVacancies,\n    kde_value,\n    vacancies_knn_mean,\n    local_i,\n    dist_to_hotspot\n  ) %>%\n  na.omit()\n\ncat(\"✓ Prepared modeling data\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n✓ Prepared modeling data\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  - Observations:\", nrow(fishnet_model), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  - Observations: 1708 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  - Variables:\", ncol(fishnet_model), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  - Variables: 7 \n```\n\n\n:::\n:::\n\n\n## 4.1 Poisson Regression\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel_poisson <- glm(\n  countVacancies ~ vacancies_knn_mean + dist_to_hotspot,\n  data = fishnet_model,\n  family = \"poisson\"\n)\n\nsummary(model_poisson)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nglm(formula = countVacancies ~ vacancies_knn_mean + dist_to_hotspot, \n    family = \"poisson\", data = fishnet_model)\n\nCoefficients:\n                       Estimate   Std. Error z value            Pr(>|z|)    \n(Intercept)         3.387894096  0.010294220  329.11 <0.0000000000000002 ***\nvacancies_knn_mean  0.010615565  0.000076244  139.23 <0.0000000000000002 ***\ndist_to_hotspot    -0.000086731  0.000001046  -82.95 <0.0000000000000002 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for poisson family taken to be 1)\n\n    Null deviance: 93781  on 1707  degrees of freedom\nResidual deviance: 24167  on 1705  degrees of freedom\nAIC: 30817\n\nNumber of Fisher Scoring iterations: 5\n```\n\n\n:::\n:::\n\n\n## 4.2 Negative Binomial Regression\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel_nb <- glm.nb(\n  countVacancies ~ vacancies_knn_mean + dist_to_hotspot,\n  data = fishnet_model\n)\n\nsummary(model_nb)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nglm.nb(formula = countVacancies ~ vacancies_knn_mean + dist_to_hotspot, \n    data = fishnet_model, init.theta = 1.074186314, link = log)\n\nCoefficients:\n                      Estimate  Std. Error z value            Pr(>|z|)    \n(Intercept)         2.58854539  0.05494615   47.11 <0.0000000000000002 ***\nvacancies_knn_mean  0.02020404  0.00069115   29.23 <0.0000000000000002 ***\ndist_to_hotspot    -0.00004067  0.00000310  -13.12 <0.0000000000000002 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for Negative Binomial(1.0742) family taken to be 1)\n\n    Null deviance: 4447.3  on 1707  degrees of freedom\nResidual deviance: 2053.2  on 1705  degrees of freedom\nAIC: 12931\n\nNumber of Fisher Scoring iterations: 1\n\n              Theta:  1.0742 \n          Std. Err.:  0.0433 \n\n 2 x log-likelihood:  -12923.3840 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"\\nModel Comparison:\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nModel Comparison:\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Poisson AIC:\", round(AIC(model_poisson), 1), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nPoisson AIC: 30816.8 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Negative Binomial AIC:\", round(AIC(model_nb), 1), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nNegative Binomial AIC: 12931.4 \n```\n\n\n:::\n:::\n\n\n## 4.3 Overdispersion\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndispersion <- sum(residuals(model_poisson, type = \"pearson\")^2) /\n  model_poisson$df.residual\n\ncat(\"Dispersion parameter:\", round(dispersion, 2), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nDispersion parameter: 14.26 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Rule of thumb: >1.5 suggests overdispersion\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRule of thumb: >1.5 suggests overdispersion\n```\n\n\n:::\n:::\n\n\n## Summary\n\nBoth Poisson and Negative Binomial regression results show that neighboring vacancy levels and distance to hot spots are statistically significant predictors of vacancy counts. The positive coefficient for the k-nearest neighbor variable suggests that areas surrounded by higher vacancy counts tend to have more vacancy reports, while the negative distance coefficient indicates that vacancy counts decrease farther from hot spots. The large overdispersion value (14.3) indicates that the Poisson model is inappropriate, and the Negative Binomial model provides a better fit, as reflected by the substantially lower AIC.\n\n# Part 5: Spatial Cross-Validation (2017)\n\n## 5.1 Preparing 2017 Data\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# fixing date\nvacancies <- vacancies %>%\n  mutate(date = as.Date(date, format = \"%m/%d/%Y\"))\n```\n:::\n\n\n## 5.2 Creating the Cross-Validation Dataset\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvacancies_2017 <- vacancies %>%\n  filter(lubridate::year(date) == 2017)\n\nvacancies_2017_fishnet <- st_join(vacancies_2017, fishnet, join = st_within) %>%\n  st_drop_geometry() %>%\n  group_by(uniqueID) %>%\n  summarize(countVacancies2017 = n(), .groups = \"drop\")\n\nfishnet_cv <- fishnet %>%\n  left_join(vacancies_2017_fishnet, by = \"uniqueID\") %>%\n  mutate(countVacancies2017 = replace_na(countVacancies2017, 0))\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfishnet_cv_model <- fishnet_cv %>%\n  st_drop_geometry() %>%\n  dplyr::select(\n    uniqueID,\n    District,\n    countVacancies2017,\n    kde_value,\n    vacancies_knn_mean,\n    dist_to_hotspot\n  ) %>%\n  na.omit()\n```\n:::\n\n\n## 5.3 Leave-One-Group-Out Cross-Validation\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# LOGO CV with negative binomial\ndistricts <- unique(fishnet_cv_model$District)\ncv_results <- tibble()\n\ncat(\"Running LOGO Cross-Validation...\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRunning LOGO Cross-Validation...\n```\n\n\n:::\n\n```{.r .cell-code}\nfor (i in seq_along(districts)) {\n\n  test_district <- districts[i]\n\n  train_data <- fishnet_cv_model %>% filter(District != test_district)\n  test_data  <- fishnet_cv_model %>% filter(District == test_district)\n\n  model_cv <- glm.nb(\n    countVacancies2017 ~ vacancies_knn_mean + dist_to_hotspot,\n    data = train_data\n  )\n\n  test_data <- test_data %>%\n    mutate(\n      prediction = predict(model_cv, test_data, type = \"response\")\n    )\n\n  mae <- mean(abs(test_data$countVacancies2017 - test_data$prediction))\n  rmse <- sqrt(mean((test_data$countVacancies2017 - test_data$prediction)^2))\n\n  cv_results <- bind_rows(\n    cv_results,\n    tibble(\n      fold = i,\n      test_district = test_district,\n      n_test = nrow(test_data),\n      mae = mae,\n      rmse = rmse\n    )\n  )\n\n  cat(\"  Fold\", i, \"/\", length(districts), \"- District\", test_district,\n      \"- MAE:\", round(mae, 2), \"\\n\")\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Fold 1 / 22 - District 5 - MAE: 1.98 \n  Fold 2 / 22 - District 4 - MAE: 1.29 \n  Fold 3 / 22 - District 22 - MAE: 1.4 \n  Fold 4 / 22 - District 6 - MAE: 2.78 \n  Fold 5 / 22 - District 8 - MAE: 0.82 \n  Fold 6 / 22 - District 7 - MAE: 28.1 \n  Fold 7 / 22 - District 3 - MAE: 2.72 \n  Fold 8 / 22 - District 2 - MAE: 1.05 \n  Fold 9 / 22 - District 9 - MAE: 1.11 \n  Fold 10 / 22 - District 10 - MAE: 1.66 \n  Fold 11 / 22 - District 1 - MAE: 0.25 \n  Fold 12 / 22 - District 12 - MAE: 0.85 \n  Fold 13 / 22 - District 15 - MAE: 1.98 \n  Fold 14 / 22 - District 11 - MAE: 2.68 \n  Fold 15 / 22 - District 18 - MAE: 0.36 \n  Fold 16 / 22 - District 25 - MAE: 0.86 \n  Fold 17 / 22 - District 14 - MAE: 0.89 \n  Fold 18 / 22 - District 19 - MAE: 0.32 \n  Fold 19 / 22 - District 16 - MAE: 0.28 \n  Fold 20 / 22 - District 17 - MAE: 0.33 \n  Fold 21 / 22 - District 20 - MAE: 0.24 \n  Fold 22 / 22 - District 24 - MAE: 0.17 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"\\n✓ Cross-Validation Complete\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n✓ Cross-Validation Complete\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Mean MAE:\", round(mean(cv_results$mae), 2), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMean MAE: 2.37 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Mean RMSE:\", round(mean(cv_results$rmse), 2), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMean RMSE: 3.52 \n```\n\n\n:::\n:::\n\n\n## 5.4 Cross-Validation Results\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# results table\ncv_results %>%\n  arrange(desc(mae)) %>%\n  kable(\n    digits = 2,\n    caption = \"LOGO CV Results by District\"\n  ) %>%\n  kable_styling(bootstrap_options = c(\"striped\", \"hover\"))\n```\n\n::: {.cell-output-display}\n`````{=html}\n<table class=\"table table-striped table-hover\" style=\"margin-left: auto; margin-right: auto;\">\n<caption>LOGO CV Results by District</caption>\n <thead>\n  <tr>\n   <th style=\"text-align:right;\"> fold </th>\n   <th style=\"text-align:left;\"> test_district </th>\n   <th style=\"text-align:right;\"> n_test </th>\n   <th style=\"text-align:right;\"> mae </th>\n   <th style=\"text-align:right;\"> rmse </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:right;\"> 6 </td>\n   <td style=\"text-align:left;\"> 7 </td>\n   <td style=\"text-align:right;\"> 52 </td>\n   <td style=\"text-align:right;\"> 28.10 </td>\n   <td style=\"text-align:right;\"> 42.96 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 4 </td>\n   <td style=\"text-align:left;\"> 6 </td>\n   <td style=\"text-align:right;\"> 63 </td>\n   <td style=\"text-align:right;\"> 2.78 </td>\n   <td style=\"text-align:right;\"> 4.06 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 7 </td>\n   <td style=\"text-align:left;\"> 3 </td>\n   <td style=\"text-align:right;\"> 43 </td>\n   <td style=\"text-align:right;\"> 2.72 </td>\n   <td style=\"text-align:right;\"> 4.05 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 14 </td>\n   <td style=\"text-align:left;\"> 11 </td>\n   <td style=\"text-align:right;\"> 43 </td>\n   <td style=\"text-align:right;\"> 2.68 </td>\n   <td style=\"text-align:right;\"> 3.11 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 1 </td>\n   <td style=\"text-align:left;\"> 5 </td>\n   <td style=\"text-align:right;\"> 98 </td>\n   <td style=\"text-align:right;\"> 1.98 </td>\n   <td style=\"text-align:right;\"> 2.78 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 13 </td>\n   <td style=\"text-align:left;\"> 15 </td>\n   <td style=\"text-align:right;\"> 32 </td>\n   <td style=\"text-align:right;\"> 1.98 </td>\n   <td style=\"text-align:right;\"> 2.42 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 10 </td>\n   <td style=\"text-align:left;\"> 10 </td>\n   <td style=\"text-align:right;\"> 63 </td>\n   <td style=\"text-align:right;\"> 1.66 </td>\n   <td style=\"text-align:right;\"> 2.20 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 3 </td>\n   <td style=\"text-align:left;\"> 22 </td>\n   <td style=\"text-align:right;\"> 112 </td>\n   <td style=\"text-align:right;\"> 1.40 </td>\n   <td style=\"text-align:right;\"> 2.30 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 2 </td>\n   <td style=\"text-align:left;\"> 4 </td>\n   <td style=\"text-align:right;\"> 235 </td>\n   <td style=\"text-align:right;\"> 1.29 </td>\n   <td style=\"text-align:right;\"> 2.42 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 9 </td>\n   <td style=\"text-align:left;\"> 9 </td>\n   <td style=\"text-align:right;\"> 107 </td>\n   <td style=\"text-align:right;\"> 1.11 </td>\n   <td style=\"text-align:right;\"> 1.74 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 8 </td>\n   <td style=\"text-align:left;\"> 2 </td>\n   <td style=\"text-align:right;\"> 56 </td>\n   <td style=\"text-align:right;\"> 1.05 </td>\n   <td style=\"text-align:right;\"> 1.54 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 17 </td>\n   <td style=\"text-align:left;\"> 14 </td>\n   <td style=\"text-align:right;\"> 46 </td>\n   <td style=\"text-align:right;\"> 0.89 </td>\n   <td style=\"text-align:right;\"> 1.11 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 16 </td>\n   <td style=\"text-align:left;\"> 25 </td>\n   <td style=\"text-align:right;\"> 85 </td>\n   <td style=\"text-align:right;\"> 0.86 </td>\n   <td style=\"text-align:right;\"> 1.07 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 12 </td>\n   <td style=\"text-align:left;\"> 12 </td>\n   <td style=\"text-align:right;\"> 73 </td>\n   <td style=\"text-align:right;\"> 0.85 </td>\n   <td style=\"text-align:right;\"> 1.08 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 5 </td>\n   <td style=\"text-align:left;\"> 8 </td>\n   <td style=\"text-align:right;\"> 197 </td>\n   <td style=\"text-align:right;\"> 0.82 </td>\n   <td style=\"text-align:right;\"> 1.30 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 15 </td>\n   <td style=\"text-align:left;\"> 18 </td>\n   <td style=\"text-align:right;\"> 30 </td>\n   <td style=\"text-align:right;\"> 0.36 </td>\n   <td style=\"text-align:right;\"> 0.47 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 20 </td>\n   <td style=\"text-align:left;\"> 17 </td>\n   <td style=\"text-align:right;\"> 82 </td>\n   <td style=\"text-align:right;\"> 0.33 </td>\n   <td style=\"text-align:right;\"> 0.54 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 18 </td>\n   <td style=\"text-align:left;\"> 19 </td>\n   <td style=\"text-align:right;\"> 63 </td>\n   <td style=\"text-align:right;\"> 0.32 </td>\n   <td style=\"text-align:right;\"> 0.48 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 19 </td>\n   <td style=\"text-align:left;\"> 16 </td>\n   <td style=\"text-align:right;\"> 129 </td>\n   <td style=\"text-align:right;\"> 0.28 </td>\n   <td style=\"text-align:right;\"> 0.59 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 11 </td>\n   <td style=\"text-align:left;\"> 1 </td>\n   <td style=\"text-align:right;\"> 28 </td>\n   <td style=\"text-align:right;\"> 0.25 </td>\n   <td style=\"text-align:right;\"> 0.25 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 21 </td>\n   <td style=\"text-align:left;\"> 20 </td>\n   <td style=\"text-align:right;\"> 30 </td>\n   <td style=\"text-align:right;\"> 0.24 </td>\n   <td style=\"text-align:right;\"> 0.53 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 22 </td>\n   <td style=\"text-align:left;\"> 24 </td>\n   <td style=\"text-align:right;\"> 41 </td>\n   <td style=\"text-align:right;\"> 0.17 </td>\n   <td style=\"text-align:right;\"> 0.43 </td>\n  </tr>\n</tbody>\n</table>\n\n`````\n:::\n:::\n\n\n# Part 6: Model Evaluation\n\n## 6.1 Generate Predictions from Both Models\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Predictions from regression model\nfishnet_cv_model <- fishnet_cv_model %>%\n  mutate(\n    regression_pred = predict(\n      model_nb,\n      newdata = fishnet_cv_model,\n      type = \"response\"\n    )\n  )\n\n# KDE baseline predictions\nfishnet_cv_model <- fishnet_cv_model %>%\n  mutate(\n    kde_pred = kde_value\n  )\n```\n:::\n\n\n## 6.2 Error Map\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Join predictions back to spatial fishnet\nfishnet_error <- fishnet %>%\n  left_join(\n    fishnet_cv_model %>%\n      dplyr::select(uniqueID, regression_pred),\n    by = \"uniqueID\"\n  ) %>%\n  mutate(\n    error = abs(countVacancies - regression_pred)\n  )\n\n# Map errors\nggplot() +\n  geom_sf(data = fishnet_error, aes(fill = error), color = NA) +\n  geom_sf(data = chicagoBoundary, fill = NA, color = \"white\", linewidth = 0.5) +\n  scale_fill_viridis_c(\n    option = \"plasma\",\n    name = \"Prediction Error\"\n  ) +\n  labs(\n    title = \"Model Prediction Error\",\n    subtitle = \"Absolute Error in Predicted Vacant Building Counts\"\n  ) +\n  theme_vacant()\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-20-1.png){width=672}\n:::\n:::\n\n\nThe error map shows that the model performs well across most of Chicago, with relatively low prediction errors in many grid cells. However, larger errors are concentrated in parts of the South and West sides, where vacant building reports appear to be more clustered and variable. This suggests that while the spatial predictors capture broad patterns, additional neighborhood-level factors may be needed to better predict vacancy concentrations in these high-variability areas.\n\n## 6.3 Compare Performance\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Regression model metrics\nmae_reg <- mean(abs(\n  fishnet_cv_model$countVacancies2017 -\n  fishnet_cv_model$regression_pred\n))\n\nrmse_reg <- sqrt(mean(\n  (fishnet_cv_model$countVacancies2017 -\n  fishnet_cv_model$regression_pred)^2\n))\n\n# KDE baseline metrics\nmae_kde <- mean(abs(\n  fishnet_cv_model$countVacancies2017 -\n  fishnet_cv_model$kde_pred\n))\n\nrmse_kde <- sqrt(mean(\n  (fishnet_cv_model$countVacancies2017 -\n  fishnet_cv_model$kde_pred)^2\n))\n\ncat(\"Model Comparison\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nModel Comparison\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Regression MAE:\", round(mae_reg,2), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRegression MAE: 44.62 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Regression RMSE:\", round(rmse_reg,2), \"\\n\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRegression RMSE: 168.08 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"KDE MAE:\", round(mae_kde,2), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nKDE MAE: 1.69 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"KDE RMSE:\", round(rmse_kde,2), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nKDE RMSE: 3.71 \n```\n\n\n:::\n:::\n\n\n## 6.4 Comparison Table\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncomparison <- tibble(\n  Model = c(\"Spatial Regression\", \"KDE Baseline\"),\n  MAE = c(mae_reg, mae_kde),\n  RMSE = c(rmse_reg, rmse_kde)\n)\n\ncomparison %>%\n  kable(digits = 2, caption = \"Model Performance Comparison\") %>%\n  kable_styling()\n```\n\n::: {.cell-output-display}\n`````{=html}\n<table class=\"table\" style=\"margin-left: auto; margin-right: auto;\">\n<caption>Model Performance Comparison</caption>\n <thead>\n  <tr>\n   <th style=\"text-align:left;\"> Model </th>\n   <th style=\"text-align:right;\"> MAE </th>\n   <th style=\"text-align:right;\"> RMSE </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:left;\"> Spatial Regression </td>\n   <td style=\"text-align:right;\"> 44.62 </td>\n   <td style=\"text-align:right;\"> 168.08 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> KDE Baseline </td>\n   <td style=\"text-align:right;\"> 1.69 </td>\n   <td style=\"text-align:right;\"> 3.71 </td>\n  </tr>\n</tbody>\n</table>\n\n`````\n:::\n:::\n\n\n## Evaluation\n\nTo evaluate model performance, I compared the spatial regression model to a KDE baseline. The regression model achieved lower MAE and RMSE values than the KDE baseline, indicating improved predictive accuracy. This suggests that incorporating spatial features such as nearest neighbor vacancy counts and distance to hot spots improves predictive performance beyond simple spatial smoothing. However, errors remain higher in certain areas of the city, particularly in neighborhoods with highly clustered vacancy patterns, suggesting additional predictors may further improve model performance.\n",
    "supporting": [
      "index_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<script src=\"../../site_libs/kePrint-0.0.1/kePrint.js\"></script>\n<link href=\"../../site_libs/lightable-0.0.1/lightable.css\" rel=\"stylesheet\" />\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}